### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by smalltownhikk18** [tweakunwanted/OpenXC-Player#1]

**Comment by tweakunwanted** [comment]
![image](https://user-images.githubusercontent.com/56216907/66614072-f1c31e80-eb9d-11e9-93ad-81610630685a.png)

![image](https://user-images.githubusercontent.com/56216907/66614142-3484f680-eb9e-11e9-9c54-4388fa865bae.png)

![image](https://user-images.githubusercontent.com/56216907/66614200-731ab100-eb9e-11e9-8bc5-3731e55690ac.png)
